function uimwrite(I)
%%Ð´ÈëÍ¼Æ¬º¯Êý
global old_pw
if old_pw==0
    old_pw=[];
end
 [fn, pn] = uiputfile( ...
       {'*.bmp;*.jpg;*.tiff;*.gif;*.png', 'Image format (*.bmp, *.jpg, *.tiff, *.gif, *.png)';...
       '*.bmp', '*.bmp';...
         '*.jpg','*.fig';...
         '*.tiff','*.tiff';...
         '*.gif','*.gif';...
         '*.png','*.png';...
         '*.*',  'all(*.*)'},'Save image',old_pw);
     old_pw=pn;
if isequal(fn,0)||isequal(pn,0)
    return;
end
imwrite(uint8(I),[pn,fn]);